### ISSUE TITLE
Columns++ does not add to search bar in secondary instances

### ISSUE THREAD

**Issue by molsonkiko** [Coises/ColumnsPlusPlus#2]
Really happy with some of the features of this plugin so far, and interested to see what I can do with it.

I think it's cool that I can add Columns++ to the main search bar. Definitely simplifies use of the plugin. But when I create a new instance, Columns++ is not on the search bar.

AFAIK that's the only bug with multi-instance/multi-view.

![image](https://user-images.githubusercontent.com/46202915/230787744-8c3f51f4-4e02-410d-a814-215bec839baf.png)

**Comment by Coises** [comment]
Thank you for your report, and your encouragement.

This happens because the plugin doesn't save its settings until you close an instance. I think that so long as the last instance you closed had it on the menu bar, new instances will put it there automatically.

However... I didn't even think about multiple instances until just now. I have that option in Notepad++ turned off, and literally forgot that it was there. There will probably be other strange behaviors. At best, instances will overwrite each other's updates to the file where persistent settings are saved, so that only the settings from the last instance closed will be retained. There could be worse problems, like crashes, depending on how this works. I will look into it.

**Comment by molsonkiko** [comment]
Yeah, I closed Notepad++ and re-opened it, and can confirm that now the Columns++ tab shows in secondary instances.

I specifically tested how it would work with multiple views/instances because I *also* never thought of that initially when I was developing my plugins, and I suspected that I wasn't alone in this regard.

**Comment by Coises** [comment]
Some investigation suggests that Notepad++ itself shares the same behavior. For example:

- Start Notepad++, be sure Word wrap is off, then close it.
- Open Notepad++.
- Turn on Word wrap.
- Open another instance of Notepad++.
- Check the View menu and note that Word wrap is off.
- If you close both instances, then open a new instance, Word wrap will have the same setting as whichever instance you closed last.

Notepad++ search history exhibits the same behavior. If you search for "what" in one instance and then open another instance, "what" will not appear in the second instance's search history. If you then search for "which" in the second instance and then close both instances, when you open Notepad++ again only the search string from the instance you closed last will be in the search history.

For now, I'm going to consider it not too unreasonable to have the same behavior that Notepad++ has. Multiple instances will be completely independent, and when you open a new instance, it will start with the settings from the last instance you closed.

After checking how this works, I don't anticipate any problematic behavior from running Columns++ in multiple instances _except_ for that.

Most of the time, it shouldn't matter. However, it will be a caution if you save Elastic tabstops profiles, add rules about enabling or disabling Elastic tabstops automatically, or rely on Columns++ search history, since when you have multiple instances open, only the changes in _one_ instance — the one you happen to close _last_ — will be retained. Clearly, this isn't ideal, but it will take me a while to develop a strategy for mitigating it.

Thank you again for the input and investigation.
