### ISSUE TITLE
Scintilla error; status code 1

### ISSUE THREAD

**Issue by Oracle255** [Coises/ColumnsPlusPlus#22]
Not sure if it's just on my end, But I get an error code "An exception occured due to plugin: CollumnPlusPlus.dll" "Exception reason: Scintilla error; status code1"... with version 1.0.5/1.0.6

**Comment by Coises** [comment]
@Oracle255 

Thank you for reporting this. I need a little more information to know where to start looking for the cause.

When does this happen? When you first open Notepad++, or after you do some particular thing? Every time or just some times?

From the main menu in Notepad++, please select **?** | **Debug Info...**, then click **Copy debug info into clipboard** and paste the copied information into a follow-up comment here.

**Comment by Oracle255** [comment]
> @Oracle255
> 
> Thank you for reporting this. I need a little more information to know where to start looking for the cause.
> 
> When does this happen? When you first open Notepad++, or after you do some particular thing? Every time or just some times?
> 
> From the main menu in Notepad++, please select **?** | **Debug Info...**, then click **Copy debug info into clipboard** and paste the copied information into a follow-up comment here.

I just get those error message on notepad launch after installing the plugin. and everytime I've use the menu from this plugin it also give me same error code. not sure if it's a conflict with my other plugin, but here's my debug info...

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.356
Current ANSI codepage : 1252
Plugins : ColumnsPlusPlus.dll ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by Coises** [comment]
@Oracle255 

I see. The problem is that Columns++ doesn’t work with versions of Notepad++ older than 8.4.3 (release date 2022-07-08).

There really is nothing I can do about that, but I did fail to make it clear in any documentation. Thank you for calling it to my attention.

The only suggestion I can make is to upgrade to the [current version of Notepad++](https://notepad-plus-plus.org/downloads/). There really have been a lot of changes and improvements in Notepad++ since the version you are running, so unless there is some reason you can’t upgrade, it’s worth doing. However, you will need to upgrade some other plugins as well. Compare has been replaced by [ComparePlus](https://github.com/pnedev/comparePlus) (same author); I’m sure [JSONViewer](https://github.com/NPP-JSONViewer/JSON-Viewer) will need to be updated. You can get both of those from **Plugins** | **Plugins Admin...** in the current version of Notepad++. MIME Tools, Converter and NPPExport are included with Notepad++ and will upgrade when you upgrade it.

**Comment by Oracle255** [comment]
> @Oracle255
> 
> I see. The problem is that Columns++ doesn’t work with versions of Notepad++ older than 8.4.3 (release date 2022-07-08).
> 
> There really is nothing I can do about that, but I did fail to make it clear in any documentation. Thank you for calling it to my attention.
> 
> The only suggestion I can make is to upgrade to the [current version of Notepad++](https://notepad-plus-plus.org/downloads/). There really have been a lot of changes and improvements in Notepad++ since the version you are running, so unless there is some reason you can’t upgrade, it’s worth doing. However, you will need to upgrade some other plugins as well. Compare has been replaced by [ComparePlus](https://github.com/pnedev/comparePlus) (same author); I’m sure [JSONViewer](https://github.com/NPP-JSONViewer/JSON-Viewer) will need to be updated. You can get both of those from **Plugins** | **Plugins Admin...** in the current version of Notepad++. MIME Tools, Converter and NPPExport are included with Notepad++ and will upgrade when you upgrade it.

I've upgrade my notepad to the current version and it worked flawlessly. thanks for recommending me an alternative for the compare plugin since I've used that a lot.. cheers
